export const ENDPOINTS = {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    USER_ME: '/users/me',

    MY_FOLLOWERS: '/users/me/followers',
    MY_FOLLOWINGS: '/users/me/followings',
    USER_FOLLOWERS: (userId: string) => `/users/${userId}/followers`,
    USER_FOLLOWINGS: (userId: string) => `/users/${userId}/followings`,
    FOLLOW_USER: (userId: string) => `/users/${userId}/follow`,
    UNFOLLOW_USER: (userId: string) => `/users/${userId}/unfollow`,

    REFRESH_TOKEN: '/auth/refresh',
    PUBLISH_BUSINESS: '/publications/business',
    GET_BUSINESS_PUBLICATIONS: '/publications/mine',
    PATCH_BUSINESS_PUBLICATION: '/publications/',
    DELETE_BUSINESS_PUBLICATION: '/publications/',
    HOTEL_ROOMPACK: '/users/me/hosting',
    RESTAURANT_MENU: '/users/me/restaurant',
    GET_OTHER_BUSINESS_PUBLICATIONS: '/publications/',
    SEARCH_BUSINESS: "/users/search/business",
    SEARCH_TRAVELERS: "/users/search/user",
    CREATE_PLAN: "/users/plans/create",
    GET_PLANS: "/users/plans/list",
    POST_REVIEW: "/publications/{id}/review",
    GET_PUBLICATION_REVIEWS: "/publications/{id}/review",
    GET_USER_REVIEWS: "/publications/users/{id}/reviews",
    DELETE_PLAN: "/users/plans/{id}",
    PATCH_PLAN: "/users/plans/{id}",
  };
  