export const ENDPOINTS = {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    USER_ME: '/users/me',    
    REFRESH_TOKEN: '/auth/refresh',
    PUBLISH_BUSINESS: '/publications/business',
    GET_BUSINESS_PUBLICATIONS: '/publications/mine',
    PATCH_BUSINESS_PUBLICATION: '/publications/',
    DELETE_BUSINESS_PUBLICATION: '/publications/',
    HOTEL_ROOMPACK: '/users/me/hosting',
    RESTAURANT_MENU: '/users/me/restaurant',
    GET_OTHER_BUSINESS_PUBLICATIONS: '/publications/',
    SEARCH_BUSINESS: "/users/search/business",
    SEARCH_TRAVELERS: "/users/search/travelers",
    CREATE_PLAN: "/users/plans/create",
    GET_PLANS: "/users/plans/list",
    POST_REVIEW: "/publications/{id}/review",
    GET_PUBLICATION_REVIEWS: "/publications/{id}/review",
    GET_USER_REVIEWS: "/publications/users/{id}/reviews",
  };
  